[package]
name = "sertifichain_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.17"
ic-cdk-macros = "0.17"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]